### PR TITLE
copy typings file to dist uppon build.

### PR DESCRIPTION
**Pull request by omerman**

### CODE REVIEW

**Comment by omerman** [comment]
@LeonardoGentile Im not sure why my pr is failing, it says something about node 8 checks passing and node  checks failing.. help?

**Comment by omerman** [comment]
@LeonardoGentile Not sure why node 6 env won't pass.. Have you encountered this error before?

**Comment by LeonardoGentile** [comment]
@omerman not that I remember 🤔 
The problem seems 
```
npm WARN prepare removing existing node_modules/ before installation
npm ERR! code MODULE_NOT_FOUND
npm ERR! Cannot find module '../pack.js'
```

Maybe an npm or travis problem?

**Comment by omerman** [comment]
It stopped working after I used `git commit --amend`.. and added some code(made the code prettier and added a comment on top of the code) to the first commit.. I think maybe re-opening this pr will maybe make it work :neutral_face:

**Comment by omerman** [comment]
@LeonardoGentile It passes now.. #13 
I guess it happens when Travis runs on a pr more than once? weird..

**Pull request closed without merging**
