### PR TITLE
Copy typings file to dist

### PR DESCRIPTION
**Pull request by omerman**
Copying the typings file to dist as part of the build.

### CODE REVIEW

**Comment by LeonardoGentile** [comment]
Apparently this is still randomly failing on travis after I've integrated it in my branch.
At this point I think it's something travis-related.. but I'm not sure what/why

**Comment by omerman** [comment]
It happens when Travis runs more than once on the same branch

**Comment by LeonardoGentile** [comment]
Really? Why should it? 
It's now failing on node 6 because it can't find eslint..?
```
sh: 1: eslint: not found
npm ERR! Linux 4.14.12-041412-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v6.14.4/bin/node" "/home/travis/.nvm/versions/node/v6.14.4/bin/npm" "run" "lint"
npm ERR! node v6.14.4
npm ERR! npm  v3.10.10
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! mobx-router5@0.0.0-development lint: `eslint src test tools`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the mobx-router5@0.0.0-development lint script 'eslint src test tools'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mobx-router5 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint src test tools
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mobx-router5
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mobx-router5
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/LeonardoGentile/mobx-router5/npm-debug.log
The command "npm run lint" exited with 1.
```
I think it's a travis problem.

How would you fix this? Make another fake commit and run it again?

**Comment by omerman** [comment]
Well it is not what we saw earlier.. But what solved it for me was to close the pr and open another one.
So Im not really sure how should you proceed.. maybe open a branch with the changes, push it, and then merge to master?

**Comment by omerman** [comment]
If nothing works, maybe give up on the node 6 checks temporarily, and report to Travis :X? 

I saw this [Issue](https://github.com/LLK/scratch-vm/issues/1238) on Travis..

**Comment by LeonardoGentile** [comment]
it was totally a travis problem, by purging the cache each time it temporarily fixed the following build  🙄

**Pull request merged**
