### PR TITLE
fix: Added @action decorator to updateRoute and resetRoute methods of…

### PR DESCRIPTION
**Pull request by aap82**
… RouterStore as they directly m

### CODE REVIEW

**Comment by LeonardoGentile** [comment]
Thanks for this 👍 
I will take a look and test it this weekend

**Comment by LeonardoGentile** [comment]
I would say this was not necessary because the two methods `updateRoute` and `resetRoute` are always called from other methods already decorated with `@action`, isn't it?

Do you have the need to call these two methods from outside the store instance?

**Comment by aap82** [comment]
You're right that it's probably not necessary, but it just made sense to me to have it wrapped in the event that I or anyone else want to use it directly.  But no, I do not have the need for it at the moment.

On a side note though, I think that these
```
  @observable route = null;
  @observable previousRoute = null;
  @observable transitionRoute = null;
```
should be actually be
```
  @observable.ref route = null;
  @observable.ref previousRoute = null;
  @observable.ref transitionRoute = null;
```
because the route properties themselves are never mutated, as they are replaced in whole.  So, there isnt really a need to mark the properties observable, just the reference.    Thoughts?

**Comment by LeonardoGentile** [comment]
I'm closing this as updateRoute and resetRoute are intended as helpers and always called from other @action decorated methods.

I will implement the @observable.ref soon

**Pull request closed without merging**
